name: SQL Server CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build DACPAC
        run: msbuild db/MyDatabase/MyDatabase/MyDatabase.sqlproj /p:Configuration=Release

      - name: Install SqlPackage
        run: dotnet tool install -g microsoft.sqlpackage

      - name: Deploy DACPAC to SQL Server
        if: github.ref == 'refs/heads/main'
        env:
          DOTNET_ROLL_FORWARD: LatestMajor
        run: |
          sqlpackage /Action:Publish `
            /SourceFile:"db/MyDatabase/MyDatabase/bin/Release/MyDatabase.dacpac" `
            /TargetServerName:"localhost" `
            /TargetDatabaseName:"BooksDB" `
            /TargetTrustServerCertificate:true